version: '3'
services:
  strongswan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: strongswan-container
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    restart: always
